"""Pydantic data models for the Opportunity Radar pipeline."""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────────────────────

class FilingType(str, Enum):
    DRHP = "DRHP"
    AGM = "AGM"
    PLEDGE = "PLEDGE"
    INSIDER_TRADE = "INSIDER_TRADE"
    BULK_DEAL = "BULK_DEAL"
    BLOCK_DEAL = "BLOCK_DEAL"
    BOARD_MEETING = "BOARD_MEETING"
    QUARTERLY_RESULT = "QUARTERLY_RESULT"
    CORPORATE_ACTION = "CORPORATE_ACTION"
    SHAREHOLDING = "SHAREHOLDING"


class SignalType(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    WATCH = "WATCH"


class AlertPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class FeedbackAction(str, Enum):
    DISMISS = "DISMISS"
    WATCH = "WATCH"
    BUY_SIGNAL = "BUY_SIGNAL"
    SELL_SIGNAL = "SELL_SIGNAL"


# ── Pipeline Models ──────────────────────────────────────────────────────────

class RawFiling(BaseModel):
    """Emitted by Filing Watcher → raw_filings topic."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    source: str  # "NSE", "BSE", "SEBI"
    filing_type: FilingType
    company_name: str
    stock_symbol: str
    title: str
    summary: str
    raw_text: str = ""
    source_url: str = ""
    filed_at: datetime = Field(default_factory=datetime.utcnow)
    ingested_at: datetime = Field(default_factory=datetime.utcnow)
    content_hash: str = ""
    data_freshness_ms: int = 0


class DimensionScores(BaseModel):
    """5-dimension scoring for signal classification."""
    magnitude: float = Field(ge=0, le=1, description="Size/impact of the event")
    insider_credibility: float = Field(ge=0, le=1, description="Credibility of insider/source")
    timing: float = Field(ge=0, le=1, description="Timing significance")
    sector_momentum: float = Field(ge=0, le=1, description="Sector trend alignment")
    historical_match: float = Field(ge=0, le=1, description="Match with past profitable patterns")


class ClassifiedSignal(BaseModel):
    """Returned by Signal Classifier → classified_signals topic."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    filing_id: str
    signal_type: SignalType
    importance_score: float = Field(ge=0, le=1)
    dimension_scores: DimensionScores
    affected_stocks: list[str] = []
    tags: list[str] = []
    reasoning: str = ""
    classified_at: datetime = Field(default_factory=datetime.utcnow)


class PeerComparison(BaseModel):
    """Peer stock comparison data."""
    symbol: str
    name: str
    pe_ratio: float = 0
    market_cap_cr: float = 0
    ytd_return_pct: float = 0


class EnrichedSignal(BaseModel):
    """Returned by Context Enrichment → enriched_signals topic."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    signal: ClassifiedSignal
    filing: RawFiling
    current_price: float = 0
    price_change_1d_pct: float = 0
    price_change_1w_pct: float = 0
    price_change_1m_pct: float = 0
    pe_ratio: float = 0
    eps: float = 0
    market_cap_cr: float = 0
    sector: str = ""
    peers: list[PeerComparison] = []
    impact_analysis: str = ""  # LLM-generated "so what?"
    enriched_at: datetime = Field(default_factory=datetime.utcnow)


class Alert(BaseModel):
    """Final alert generated by Alert Composer → alerts topic."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    enriched_signal_id: str
    stock_symbol: str
    company_name: str
    signal_type: SignalType
    priority: AlertPriority
    confidence_score: float = Field(ge=0, le=1)
    title: str
    body: str  # Plain-English alert
    risk_flags: list[str] = []
    historical_base_rate: str = ""  # e.g. "72% of similar signals saw 5%+ move in 30 days"
    tags: list[str] = []
    needs_human_review: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)
    data_freshness_ms: int = 0
    filing_type: str = ""
    dimension_scores: Optional[DimensionScores] = None


class UserProfile(BaseModel):
    """User profile with watchlist and preferences."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    name: str
    email: str = ""
    watchlist: list[str] = []  # stock symbols
    sectors: list[str] = []
    notification_prefs: dict = Field(default_factory=lambda: {
        "push": True, "email": False, "in_app": True
    })


class FeedbackEvent(BaseModel):
    """User feedback on an alert — flows back to classifier."""
    id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    alert_id: str
    user_id: str
    action: FeedbackAction
    timestamp: datetime = Field(default_factory=datetime.utcnow)


# ── API Response Models ──────────────────────────────────────────────────────

class PipelineStatus(BaseModel):
    """Health status of the agent pipeline."""
    filing_watcher: str = "idle"
    signal_classifier: str = "idle"
    context_enricher: str = "idle"
    alert_composer: str = "idle"
    orchestrator: str = "idle"
    total_filings_processed: int = 0
    total_signals_generated: int = 0
    total_alerts_sent: int = 0
    uptime_seconds: float = 0
